name: Push-to-EC2

on:
  push:
    branches:
      - main # Ou a branch que você usa para deploy (ex: master, production)

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest # O runner do GitHub Actions pode ser ubuntu-latest

    steps:
      - name: 📂 Checkout do código
        uses: actions/checkout@v4 # Use a versão mais recente para melhorias e segurança

        
      - name: 🚚 Copiar arquivos para EC2 via SSH
        uses: easingthemes/ssh-deploy@main # Ou appleboy/scp-action@master
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete" # Opções comuns do rsync
          SOURCE: "./" # Copiar todo o conteúdo do repositório
          REMOTE_HOST: "ec2-54-87-188-178.compute-1.amazonaws.com"  # Seu DNS público: ec2-3-83-46-84.compute-1.amazonaws.com
          REMOTE_USER: "ubuntu" # Provavelmente 'ubuntu' para Ubuntu 22.04
          TARGET: "/home/ubuntu/var/www/html/projeto" # Ex: /var/www/html/seu-app-laravel
          EXCLUDE: "/dist/, /node_modules/, .git*, .github*, vendor/, storage/logs/*, storage/framework/sessions/*, storage/framework/cache/data/*, storage/framework/views/*, bootstrap/cache/*.php, **.env"